#!/usr/bin/env python
import os
import sys

env = SConscript("thirdparty/godot-cpp/SConstruct")

env["ML_SOURCES"]  = []
env["ONNX_SOURCES"] = []

# Thirdparty 
SConscript("thirdparty/SCsub", exports="env")

# ML Runtime
SConscript("ml/SCsub", exports="env")

# Include paths + libs
env.Append(CPPPATH=env.get("ML_INCLUDE_PATHS", []))
env.Append(CPPPATH=env.get("ONNX_INCLUDE_PATHS", []))

if "ML_ENV" in env:
    env.Append(LIBS=env["ML_ENV"]["LIBS"])
    env.Append(LIBPATH=env["ML_ENV"].get("LIBPATH", []))

# Extension library
sources = (
    ["register_types.cpp"]
    + env.get("ML_SOURCES", [])
    + env.get("ONNX_SOURCES", [])
)

lib_base_name = "libml"
demo_bin = "../demo/addons/ml/bin/"

if env["platform"] == "macos":
    target_path = "{}{}.{}.{}.framework/{}".format(
        demo_bin, lib_base_name, env["platform"], env["target"], lib_base_name
    )
    library = env.SharedLibrary(target_path, source=sources)
elif env["platform"] == "ios":
    suffix      = ".simulator.a" if env["ios_simulator"] else ".a"
    target_path = "{}{}.{}.{}{}".format(
        demo_bin, lib_base_name, env["platform"], env["target"], suffix
    )
    library = env.StaticLibrary(target_path, source=sources)
else:
    target_path = "{}{}{}{}".format(
        demo_bin, lib_base_name, env["suffix"], env["SHLIBSUFFIX"]
    )
    library = env.SharedLibrary(target_path, source=sources)

Default(library)